### ISSUE TITLE
seat icon not displaying in qgis gui toolbar. 

### ISSUE THREAD

**Issue by tnelson-integral** [IntegralEnvision/seat-qgis-plugin#6]
Shows a gray box instead of seat icon in toolbar.
![image](https://user-images.githubusercontent.com/104927621/189174301-ec16b769-82cf-435a-90fe-d666f013c95b.png)

**Comment by geocoug** [comment]
fixed via 881ad1271cbada2e6cd82406f30f4b15f51dab68
